val = [1,2,3,5,6,8,7,9,5,1,6,6,4]
print(val.index(1))
print(val.index(2))
print(val.index(3))
print(val.index(4))
print(val.index(5))
print(val.index(6))
print("-----------------------------")
#count function
print(val.count(1)) 
print(val.count(2))
print(val.count(3))
print(val.count(4))
print(val.count(5))
print(val.count(6))