print('prashantjha777'.isalnum())
print('prashantjha'.isalpha())
print('777f'.isdigit())
print('sdsdsdsd'.islower())
print(''.islower())
print('PRASHANTj'.isupper())
print('My Name Is Prashant'.istitle())
print(''.istitle())
print(' '.isspace())
print("Hello".startswith("He"))
print("Hello".endswith("lo"))